### ISSUE TITLE
Add more details to extracted timeline

### ISSUE THREAD

**Issue by tuxnco** [cogniteev/prerender#13]
- [ ] identify Type according to chrome dev tools
- [x] timing details (dns , ttfb, ttlb)
- [x] payload size
- [x] request/response headers

**Comment by tuxnco** [comment]
dns resolution time can't  be tracked from the onReseourceReceived callback.
I actually extract raw contentType on each resource, I don't know if the mapping to JS/XHR/IMG/CSS/DOC/... should be done on this side or consumer side (definition may evolve ?)

**Comment by panthony** [comment]
I think we should keep the codebase here minimal.

Simply register and returns raw metrics.

Let another layer (be it our toolbox or something else) interpret the collected data.
